locales:
  en:
    name: South Sami Keyboards
    description: >-
      Mobile OS keyboards for the South Sami language from the Divvun group
      at UiT.
  nb:
    name: Sørsamisk tastatur
    description: Mobiltastatur for sørsamisk fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga árktalaš universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga árktalaš universitehta
