locales:
  en:
    name: Southern Sami Keyboards
    description: >-
      Mobile OS keyboards for the Southern Sami language from the Divvun group
      at UiT.
  nb:
    name: Southern Sami tastatur
    description: Mobiltastatur for Southern Sami fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
