internalName: sma

locales:
  en:
    name: &bundleName "Southern Sami Keyboards"
    description: "Mobile OS keyboards for the Southern Sami language from the Divvun group at UiT."
  nb:
    name: "Southern Sami tastatur"
    description: "Mobiltastatur for Southern Sami fra Divvun-gruppa."

author: The Divvun Group, UiT Norgga 치rktala코 universitehta
email: feedback@divvun.no

copyright: (c) 2017 Divvun/Giellatekno/UiT
organisation: UiT Norgga 치rktala코 universitehta

layouts: [sma-mobile, sma_NO-macos, sma_SE-macos, sma_NO-windows, sma_SE-windows]

version: 1.0
build: 1

targets:
  android:
    packageId: no.uit.giella.keyboards.sma
    icon: images/sma-icon.pdf
    keyStore: $GTPRIV/admin/dev-accounts/dev_keys/sami_keyboard.keystore
    keyAlias: sami_keyboard

  ios: &AppleID
    codeSignId: "Developer ID Installer: The University of Tromso (2K5J2584NX)"
    provisioningProfileId: Test
    packageId: no.uit.giella
    bundleName: *bundleName
    icon: images/sma-icon.png

  osx:
    <<: *AppleID
    icon: images/sma-keyboard-menu-icon.png
    version: 1.0.0-beta2
    resources: doc
    readme: readme.html
    background: background.png

  win:
    appName: *bundleName
    version: 1.0.0-beta1
    url: "http://divvun.no"
    uuid: "26D74558-DDAD-4BCF-A65A-84C03FB63F6D"
