internalName: sma_keyboard

locales:
  en:
    name: &bundleName "Southern Sami Keyboards"
    description: "Mobile OS keyboards for the Southern Sami language from the Divvun group at UiT."
  nb:
    name: "Southern Sami tastatur"
    description: "Mobiltastatur for Southern Sami fra Divvun-gruppa."

author: The Divvun Group, UiT Norgga 치rktala코 universitehta
email: feedback@divvun.no

copyright: (c) 2017 Divvun/Giellatekno/UiT
organisation: UiT Norgga 치rktala코 universitehta

layouts: [sma-mobile, sma_NO-macos, sma_SE-macos, sma_NO-windows, sma_SE-windows]

version: 1.0
build: 1

targets:
  android:
    packageId: no.uit.giella.keyboards.sma
    icon: images/sma-icon.pdf
    keyStore: /Users/brendan/git/softkbdgen/test.keystore
    keyAlias: sma_keyboard

  ios: &AppleID
    codeSignId: "iOS Development"
    provisioningProfileId: Test
    packageId: no.uit.giella.keyboards.sma
    bundleName: *bundleName
    icon: images/sma-icon.png

  osx:
    <<: *AppleID
    icon: images/sma-keyboard-menu-icon.png
    codeSignId: "Developer ID Installer: The University of Tromso (2K5J2584NX)"
    version: 1.0.0-beta2
    resources: doc
    readme: readme.html
    background: background.png
